; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html
;

[env:lolin32]
platform = espressif32 @ 4.4.0
framework = arduino
board = lolin32
monitor_speed = 115200
upload_speed = 921600
build_flags = '-fexceptions'
; Please see "secrets.load.sample" and copy it file to secrets.load
src_build_flags = !echo "-DSRC_REV="$(git rev-list --all --count HEAD && ./secrets.load)
#extra_scripts = pre:extra_script.py
lib_deps =
    ;thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays
    ;https://github.com/mikeazo/TOTP-Arduino
    https://github.com/ThingPulse/esp8266-oled-ssd1306.git#2b4241a
    https://github.com/lucadentella/TOTP-Arduino.git#afec486

;targets = upload
; any port that starts with /dev/ttyUSB
;upload_port = /dev/ttyUSB*

; ip for OTA
;upload_port = 192.168.3.122
